@trinet @requotedQuotes @wip @fernando
Feature: New quotes created after requote a proposal
  As a Broker
  I want to requote existing BCR and PCR proposal
  So that new quotes should display correct information in census modeling

  @critical
  Scenario: WSE's with "Part Time" or "Temp" employment status should never display on new quotes created after BCR proposal requoted

  @critical
  Scenario: WSE's with "Part Time" or "Temp" employment status should never display on new quotes created after PCR proposal requoted

  @critical
  Scenario: WSE's with "Full Time" or "Member/Partner" employment status should always display on new quotes created after BCR proposal requoted

  @critical
  Scenario: WSE's with "Full Time" or "Member/Partner" employment status should always display on new quotes created after PCR proposal requoted

  @critical
  Scenario: Confirm that "Coverage Status" value should display correctly for all Employees for BCR/PCR autogenerated quotes

  @critical
  Scenario: Confirm that "Benefit Program" value should display correctly for all Employees for BCR/PCR autogenerated quotes

  @critical
  Scenario: Confirm that "State" and "Zip" value should display correctly for all Employees for BCR/PCR autogenerated quotes

  @critical
  Scenario: Confirm that "EE Rate" and "DEP Rate" value should display correctly for all Employees for Medical PCR autogenerated quotes

  @critical
  Scenario: Confirm that "EE Cost", "ER Cost" and "Total Cost" value should display correctly for all Employees for BCR/PCR autogenerated quotes

  @critical
  Scenario: Updating Benefit Program number or description ,results in Benefit Program details update for affected Employees for autogenerated quotes

  @critical
  Scenario: Deletion and assignment of Benefit Program should result in "Benefit Program" update for affected Employees for BCR/PCR autogenerated quotes

  @critical
  Scenario: Updates to Benefit Program assignment should result in Benefit Program column update for affected Employees for BCR/PCR autogenerated quotes

  @critical
  Scenario: Update to  "Coverage Status" from Census should result in "Coverage Status" update for affected Employees for BCR/PCR autogenerated quotes

  @critical
  Scenario: Update to "Coverage Status" from Census should result in Rates and Costs update for affected Employees for BCR/PCR autogenerated quotes

  @critical
  Scenario: Updates to State and/or Zip on Census should result in State and/or Zip update for affected Employees for BCR/PCR autogenerated quotes

  @critical
  Scenario: Updates to "State" and/or "Zip" on Census should result in Rates and Costs update for affected Employees for BCR/PCR autogenerated quotes

  Scenario: Any BCR/PCR autogenerated quote should always display "Census" tab

  Scenario: BCR Ancillary autogenerated quotes should display all row headers in Census Modeling section

  Scenario: PCR Ancillary autogenerated quotes should display all row headers in Census Modeling section

  Scenario: BCR Medical autogenerated quotes should display all row headers in Census Modeling section

  Scenario: PCR Medical autogenerated quotes should display all row headers in Census Modeling section
